name: idpa
channels:
  - conda-forge
dependencies:
  - matplotlib=3.10.1
  - numpy=2.2.5
  - pandas=2.2.3
  - pyarrow=20.0.0
  - scikit-learn=1.6.1
  - tqdm=4.67.1
  - ipykernel=6.29.5
  - pytorch=2.6.0
  - torchvision=0.21.0
  - pyyaml=6.0.2
  - opencv=4.11.0
  - albumentations=2.0.5
  - pretrainedmodels=0.7.4
  - fire=0.7.0
  - datasets=3.6.0
  - ipywidgets=8.1.7
  - scikit-image=0.25.2
variables:
  NO_ALBUMENTATIONS_UPDATE: "1"
