name: idpa-analysis
channels:
  - conda-forge
dependencies:
  - matplotlib=3.10.3
  - numpy=2.2.6
  - pandas=2.2.3
  - pyarrow=20.0.0
  - scipy=1.15.2
  - seaborn=0.13.2
  - ipykernel=6.29.5
  - opencv=4.11.0
